<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Form extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *授权，默认关闭
     * @return bool
     */
    public function authorize()
    {
        //可以这里设置权限验证
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *验证规则
     * @return array
     */
    public function rules()
    {
        return [
             'username' => 'required|min:2|max:10',
             'pwd' => 'required',
        ];
    }
    //自定义错误提示
//    public function messages()
//    {
////        默认继承父类的 不要
////        return parent::messages(); // TODO: Change the autogenerated stub
//        return[
//          'username.required' => '用户名不得为空',
//          'pwd.required' => '密码不得为空',
//        ];あやらぶ
//    }

    //使用默认的提示，更改语言
    public function attributes()
    {
//        return parent::attributes(); // TODO: Change the autogenerated stub
                return[
          'username' => '用户名',
          'pwd' => '密码',
        ];
    }
}
